name: "CI - Test Features"
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    paths:
      - src/**
      - test/**
      - "!**.md"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  detect-changes:
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    outputs:
      features: ${{ steps.filter.outputs.changes }}
    steps:
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            beans: ./**/beans/**
            fxy-codex: ./**/fxy-codex/**
            fxy-godot: ./**/fxy-godot/**

  test-features-changes:
    needs:
      - detect-changes
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      matrix:
        features: ${{ fromJSON(needs.detect-changes.outputs.features) }}
        baseImage: &base_images
          - mcr.microsoft.com/devcontainers/base:ubuntu
          - mcr.microsoft.com/devcontainers/base:debian
          - debian:stable-slim
    steps:
      - uses: actions/checkout@v4

      - name: "Install latest devcontainer CLI"
        run: npm install -g @devcontainers/cli

      - name: "Generating tests for '${{ matrix.features }}' against '${{ matrix.baseImage }}'"
        run: devcontainer features test --skip-scenarios -f ${{ matrix.features }} -i ${{ matrix.baseImage }} .

  test-features-changes-alpine:
    needs:
      - detect-changes
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      matrix:
        # Add features here when they support Alpine.
        features: &alpine_features
          - beans
        baseImage: &alpine_base_images
          - mcr.microsoft.com/devcontainers/base:alpine
    steps:
      - uses: actions/checkout@v4
        if: ${{ contains(fromJSON(needs.detect-changes.outputs.features), matrix.features) }}

      - name: "Install latest devcontainer CLI"
        if: ${{ contains(fromJSON(needs.detect-changes.outputs.features), matrix.features) }}
        run: npm install -g @devcontainers/cli

      - name: "Generating tests for '${{ matrix.features }}' against '${{ matrix.baseImage }}'"
        if: ${{ contains(fromJSON(needs.detect-changes.outputs.features), matrix.features) }}
        run: devcontainer features test --skip-scenarios -f ${{ matrix.features }} -i ${{ matrix.baseImage }} .

  test-scenarios-changes:
    if: ${{ github.event_name == 'pull_request' }}
    needs:
      - detect-changes
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      matrix:
        features: ${{ fromJSON(needs.detect-changes.outputs.features) }}
    steps:
      - uses: actions/checkout@v4

      - name: "Install latest devcontainer CLI"
        run: npm install -g @devcontainers/cli

      - name: "Generating tests for '${{ matrix.features }}' scenarios"
        run: devcontainer features test -f ${{ matrix.features }} --skip-autogenerated .

  test-all:
    if: ${{ github.event_name != 'pull_request' }}
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      matrix:
        features: &all_features
          - beans
          - fxy-codex
          - fxy-godot
        baseImage: *base_images
    steps:
      - uses: actions/checkout@v4

      - name: "Install latest devcontainer CLI"
        run: npm install -g @devcontainers/cli

      - name: "Generating tests for '${{ matrix.features }}' against '${{ matrix.baseImage }}'"
        run: devcontainer features test --skip-scenarios -f ${{ matrix.features }} -i ${{ matrix.baseImage }} .

  test-all-alpine:
    if: ${{ github.event_name != 'pull_request' }}
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      matrix:
        features: *alpine_features
        baseImage: *alpine_base_images
    steps:
      - uses: actions/checkout@v4

      - name: "Install latest devcontainer CLI"
        run: npm install -g @devcontainers/cli

      - name: "Generating tests for '${{ matrix.features }}' against '${{ matrix.baseImage }}'"
        run: devcontainer features test --skip-scenarios -f ${{ matrix.features }} -i ${{ matrix.baseImage }} .

  test-all-scenarios:
    if: ${{ github.event_name != 'pull_request' }}
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      matrix:
        features: *all_features
    steps:
      - uses: actions/checkout@v4

      - name: "Install latest devcontainer CLI"
        run: npm install -g @devcontainers/cli

      - name: "Generating tests for '${{ matrix.features }}' scenarios"
        run: devcontainer features test -f ${{ matrix.features }} --skip-autogenerated .
